# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Azure Pipelines

steps:
- task: PowerShell@2
  displayName: 'Run Cake Build'
  inputs:
    targetType: filePath
    filePath: ./build.ps1

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: NuGet Package'
  inputs:
    PathtoPublish: artifacts
    ArtifactName: 'NuGet Package and Binaries'