namespace Innovator.Client
{
  public enum CommandAction
  {
    ActivateActivity
    ,AddItem
    ,ApplyAML
    ,ApplyItem
    ,ApplyMethod
    ,ApplySQL
    ,ApplyUpdate
    ,BuildProcessReport
    ,CacheDiag
    ,CancelWorkflow
    ,ChangeUserPassword
    ,CheckImportedItemType
    ,ClearCache
    ,ClearHistory
    ,CloneForm
    ,CloseWorkflow
    ,CompileMethod
    ,CopyItem
    ,CopyItem2
    ,CreateItem
    ,DeleteItem
    ,DeleteUsers
    ,DeleteVersionFile
    ,DownloadFile
    ,EditItem
    ,EvaluateActivity
    ,ExecuteEscalations
    ,ExecuteReminders
    ,ExportItemType
    ,GenerateNewGUID
    ,GenerateNewGUIDEx
    ,GenerateParametersGrid
    ,GenerateRelationshipsTabbar
    ,GenerateRelationshipsTable
    ,GetAffectedItems
    ,GetAssignedActivities
    ,GetAssignedTasks
    ,GetConfigurableGridMetadata
    ,GetCurrentUserID
    ,GetFormForDisplay
    ,GetHistoryItems
    ,GetIdentityList
    ,GetItem
    ,GetItemAllVersions
    ,GetItemLastVersion
    ,GetItemNextStates
    ,GetItemRelationships
    ,GetItemTypeByFormID
    ,GetItemTypeForClient
    ,GetItemWhereUsed
    ,GetMainTreeItems
    ,GetNextSequence
    ,GetPermissionsForClient
    ,GetUsersList
    ,GetUserWorkingDirectory
    ,InstantiateWorkflow
    ,LoadCache
    ,LoadProcessInstance
    ,LoadVersionFile
    ,LockItem
    ,LogMessage
    ,LogOff
    ,MergeItem
    ,NewItem
    ,NewRelationship
    ,PopulateRelationshipsGrid
    ,PopulateRelationshipsTables
    ,ProcessReplicationQueue
    ,PromoteItem
    ,PurgeItem
    ,ReassignActivity
    ,RebuildKeyedName
    ,RebuildView
    ,ReplicationExecutionResult
    ,ResetAllItemsAccess
    ,ResetItemAccess
    ,ResetLifeCycle
    ,ResetServerCache
    ,SaveCache
    ,ServerErrorTest
    ,SetDefaultLifeCycle
    ,SetNullBooleanTo0
    ,SetUserWorkingDirectory
    ,SkipItem
    ,StartDefaultWorkflow
    ,StartNamedWorkflow
    ,StartWorkflow
    ,StoreVersionFile
    ,TransformVaultServerURL
    ,UnlockAll
    ,UnlockItem
    ,UpdateItem
    ,ValidateUser
    ,ValidateVote
    ,ValidateWorkflowMap
  }
}
