//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aras.Tools.InnovatorAdmin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aras.Tools.InnovatorAdmin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add16 {
            get {
                object obj = ResourceManager.GetObject("add16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;AML&gt;&lt;Item type=&quot;{0}&quot; action=&quot;get&quot; maxRecords=&quot;1000&quot; orderBy=&quot;keyed_name&quot; select=&quot;id,source_id,related_id&quot;&gt;{1}&lt;/Item&gt;&lt;/AML&gt;.
        /// </summary>
        internal static string Aml_ItemGet {
            get {
                return ResourceManager.GetString("Aml_ItemGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;AML&gt;&lt;Item type=&quot;ItemType&quot; action=&quot;get&quot; select=&quot;id&quot;&gt;&lt;/Item&gt;&lt;/AML&gt;.
        /// </summary>
        internal static string Aml_ItemTypes {
            get {
                return ResourceManager.GetString("Aml_ItemTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;AML&gt;&lt;Item type=&quot;PackageElement&quot; action=&quot;get&quot; select=&quot;element_id,element_type,name&quot; orderBy=&quot;element_type,name,element_id&quot;&gt;
        ///  &lt;source_id condition=&quot;in&quot;&gt;(select id
        ///from innovator.PACKAGEGROUP
        ///where SOURCE_ID = &apos;{0}&apos;)&lt;/source_id&gt;
        ///&lt;/Item&gt;&lt;/AML&gt;.
        /// </summary>
        internal static string Aml_PackageElements {
            get {
                return ResourceManager.GetString("Aml_PackageElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;AML&gt;&lt;Item type=&quot;PackageDefinition&quot; action=&quot;get&quot; select=&quot;id&quot;&gt;&lt;/Item&gt;&lt;/AML&gt;.
        /// </summary>
        internal static string Aml_Packages {
            get {
                return ResourceManager.GetString("Aml_Packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap amlStudio32 {
            get {
                object obj = ResourceManager.GetObject("amlStudio32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap amlStudio32black {
            get {
                object obj = ResourceManager.GetObject("amlStudio32black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrowLeftAllSimpleBlack16 {
            get {
                object obj = ResourceManager.GetObject("arrowLeftAllSimpleBlack16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrowLeftSimpleBlack16 {
            get {
                object obj = ResourceManager.GetObject("arrowLeftSimpleBlack16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrowRightAllSimpleBlack16 {
            get {
                object obj = ResourceManager.GetObject("arrowRightAllSimpleBlack16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrowRightSimpleBlack16 {
            get {
                object obj = ResourceManager.GetObject("arrowRightSimpleBlack16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap check32 {
            get {
                object obj = ResourceManager.GetObject("check32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap connectionEditor16 {
            get {
                object obj = ResourceManager.GetObject("connectionEditor16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap copy16 {
            get {
                object obj = ResourceManager.GetObject("copy16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap down16 {
            get {
                object obj = ResourceManager.GetObject("down16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder32 {
            get {
                object obj = ResourceManager.GetObject("folder32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap function14 {
            get {
                object obj = ResourceManager.GetObject("function14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Header {
            get {
                object obj = ResourceManager.GetObject("Header", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon InnovatorAdmin {
            get {
                object obj = ResourceManager.GetObject("InnovatorAdmin", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap innPkg32 {
            get {
                object obj = ResourceManager.GetObject("innPkg32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap install32 {
            get {
                object obj = ResourceManager.GetObject("install32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap login16 {
            get {
                object obj = ResourceManager.GetObject("login16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap manifestFolder32 {
            get {
                object obj = ResourceManager.GetObject("manifestFolder32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap packageDefinition {
            get {
                object obj = ResourceManager.GetObject("packageDefinition", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Item type=&quot;{0}&quot; action=&quot;get&quot;&gt;
        ///  &lt;modified_by_id&gt;{1}&lt;/modified_by_id&gt;
        ///  &lt;modified_on condition=&quot;gt&quot;&gt;{2}&lt;/modified_on&gt;
        ///&lt;/Item&gt;.
        /// </summary>
        internal static string RecentItems_UserId {
            get {
                return ResourceManager.GetString("RecentItems_UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Item type=&quot;{0}&quot; action=&quot;get&quot;&gt;
        ///  &lt;modified_by_id&gt;
        ///    &lt;Item type=&quot;User&quot; action=&quot;get&quot;&gt;
        ///      &lt;keyed_name condition=&quot;like&quot;&gt;*{1}*&lt;/keyed_name&gt;
        ///    &lt;/Item&gt;
        ///  &lt;/modified_by_id&gt;
        ///  &lt;modified_on condition=&quot;gt&quot;&gt;{2}&lt;/modified_on&gt;
        ///&lt;/Item&gt;.
        /// </summary>
        internal static string RecentItems_UserKeyedName {
            get {
                return ResourceManager.GetString("RecentItems_UserKeyedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap remove16 {
            get {
                object obj = ResourceManager.GetObject("remove16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search32 {
            get {
                object obj = ResourceManager.GetObject("search32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap up16 {
            get {
                object obj = ResourceManager.GetObject("up16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:arasx=&quot;http://www.aras.com/XsltExtensions/1.0&quot; xmlns:msxsl=&quot;urn:schemas-microsoft-com:xslt&quot; extension-element-prefixes=&quot;arasx msxsl&quot;&gt;
        ///  &lt;xsl:output method=&quot;xml&quot; omit-xml-declaration=&quot;yes&quot; standalone=&quot;yes&quot; indent=&quot;yes&quot;&gt;&lt;/xsl:output&gt;
        ///
        ///  &lt;xsl:template match=&quot;table&quot;&gt;
        ///    &lt;Result&gt;
        ///      &lt;xsl:for-each select=&quot;row&quot;&gt;
        ///        
        ///      &lt;/xsl:for-each&gt;
        ///    &lt;/Result&gt;
        ///  &lt;/xsl:template&gt;
        ///&lt;/xsl:stylesheet&gt;.
        /// </summary>
        internal static string Xslt_BaseImport {
            get {
                return ResourceManager.GetString("Xslt_BaseImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:arasx=&quot;http://www.aras.com/XsltExtensions/1.0&quot; xmlns:msxsl=&quot;urn:schemas-microsoft-com:xslt&quot; extension-element-prefixes=&quot;arasx msxsl&quot;&gt;
        ///  &lt;xsl:output method=&quot;xml&quot; omit-xml-declaration=&quot;yes&quot; standalone=&quot;yes&quot; indent=&quot;yes&quot;&gt;&lt;/xsl:output&gt;
        ///
        ///  &lt;xsl:template match=&quot;table&quot;&gt;
        ///    &lt;xsl:variable name=&quot;unique-files&quot; select=&quot;arasx:GetUniqueFiles(row/path)&quot; /&gt;
        ///  
        ///    &lt;xsl:variable name=&quot;file-query&quot;&gt;
        ///      &lt;Item type=&quot;File&quot; action=&quot;get [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Xslt_DocumentMergeImport {
            get {
                return ResourceManager.GetString("Xslt_DocumentMergeImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:arasx=&quot;http://www.aras.com/XsltExtensions/1.0&quot; xmlns:msxsl=&quot;urn:schemas-microsoft-com:xslt&quot; extension-element-prefixes=&quot;arasx msxsl&quot;&gt;
        ///  &lt;xsl:output method=&quot;xml&quot; omit-xml-declaration=&quot;yes&quot; standalone=&quot;yes&quot; indent=&quot;yes&quot;&gt;&lt;/xsl:output&gt;
        ///
        ///  &lt;xsl:template match=&quot;table&quot;&gt;
        ///    &lt;xsl:variable name=&quot;unique-files&quot; select=&quot;arasx:GetUniqueFiles(row/path)&quot; /&gt;
        ///  
        ///    &lt;xsl:variable name=&quot;file-query&quot;&gt;
        ///      &lt;Item type=&quot;File&quot; action=&quot;get [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Xslt_FileMergeImport {
            get {
                return ResourceManager.GetString("Xslt_FileMergeImport", resourceCulture);
            }
        }
    }
}
